/**
 * @fileoverview gRPC-Web generated client stub for control
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: control.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.control = require('./control_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.control.ControlClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.control.ControlPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.control.Request,
 *   !proto.control.Entry>}
 */
const methodDescriptor_Control_Pull = new grpc.web.MethodDescriptor(
  '/control.Control/Pull',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.control.Request,
  proto.control.Entry,
  /**
   * @param {!proto.control.Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.control.Entry.deserializeBinary
);


/**
 * @param {!proto.control.Request} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.control.Entry>}
 *     The XHR Node Readable Stream
 */
proto.control.ControlClient.prototype.pull =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/control.Control/Pull',
      request,
      metadata || {},
      methodDescriptor_Control_Pull);
};


/**
 * @param {!proto.control.Request} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.control.Entry>}
 *     The XHR Node Readable Stream
 */
proto.control.ControlPromiseClient.prototype.pull =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/control.Control/Pull',
      request,
      metadata || {},
      methodDescriptor_Control_Pull);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.control.Message,
 *   !proto.control.Response>}
 */
const methodDescriptor_Control_Control = new grpc.web.MethodDescriptor(
  '/control.Control/Control',
  grpc.web.MethodType.UNARY,
  proto.control.Message,
  proto.control.Response,
  /**
   * @param {!proto.control.Message} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.control.Response.deserializeBinary
);


/**
 * @param {!proto.control.Message} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.control.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.control.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.control.ControlClient.prototype.control =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/control.Control/Control',
      request,
      metadata || {},
      methodDescriptor_Control_Control,
      callback);
};


/**
 * @param {!proto.control.Message} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.control.Response>}
 *     Promise that resolves to the response
 */
proto.control.ControlPromiseClient.prototype.control =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/control.Control/Control',
      request,
      metadata || {},
      methodDescriptor_Control_Control);
};


module.exports = proto.control;

